# Generated by Django 5.1.4 on 2025-02-23 18:42

import datetime
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_reservation_dropoff_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='cars/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='client',
            name='driver_license_back',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='clients/driver_licenses/backs/', verbose_name='Driver License Back'),
        ),
        migrations.AlterField(
            model_name='client',
            name='driver_license_front',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='clients/driver_licenses/fronts/', verbose_name='Driver License Front'),
        ),
        migrations.AlterField(
            model_name='client',
            name='identity_card_back',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='clients/identity_cards/backs/', verbose_name='Identity Card Back'),
        ),
        migrations.AlterField(
            model_name='client',
            name='identity_card_front',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='clients/identity_cards/fronts/', verbose_name='Identity Card Front'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='clients/passports/', verbose_name='Passport Image'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_license_back',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='drivers/driver_licenses/backs/', verbose_name='Driver License Back'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_license_front',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='drivers/driver_licenses/fronts/', verbose_name='Driver License Front'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='identity_card_back',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='drivers/identity_cards/backs/', verbose_name='Identity Card Back'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='identity_card_front',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='drivers/identity_cards/fronts/', verbose_name='Identity Card Front'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='drivers/passports/', verbose_name='Passport Image'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dropoff_time',
            field=models.TimeField(default=datetime.time(18, 42, 28, 479364), verbose_name='Dropoff Time'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(default=datetime.time(18, 42, 28, 471854), verbose_name='Pickup Time'),
        ),
    ]
