# Generated by Django 5.1.4 on 2025-02-23 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_alter_car_image_alter_client_driver_license_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dropoff_time',
            field=models.TimeField(default=datetime.time(18, 42, 43, 366635), verbose_name='Dropoff Time'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(default=datetime.time(18, 42, 43, 366635), verbose_name='Pickup Time'),
        ),
    ]
