# Generated by Django 5.1.4 on 2025-02-23 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_alter_reservation_dropoff_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dropoff_time',
            field=models.TimeField(default=datetime.datetime(2025, 2, 23, 23, 11, 47, 9781, tzinfo=datetime.timezone.utc), verbose_name='Dropoff Time'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2025, 2, 23, 23, 11, 47, 9781, tzinfo=datetime.timezone.utc), verbose_name='Pickup Time'),
        ),
    ]
