# Generated by Django 5.1.4 on 2025-02-24 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0010_alter_reservation_dropoff_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rating of the client (1 to 5)', null=True, verbose_name='Client Rating'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dropoff_time',
            field=models.TimeField(default=datetime.datetime(2025, 2, 24, 0, 52, 53, 792474, tzinfo=datetime.timezone.utc), verbose_name='Dropoff Time'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2025, 2, 24, 0, 52, 53, 792474, tzinfo=datetime.timezone.utc), verbose_name='Pickup Time'),
        ),
    ]
