# Generated by Django 5.1.4 on 2025-02-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0015_alter_reservation_dropoff_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dropoff_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Dropoff Time'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Pickup Time'),
        ),
    ]
