# Generated by Django 5.1.4 on 2025-03-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0016_alter_reservation_dropoff_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='number_of_mile',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=12, verbose_name='Milage'),
        ),
        migrations.AddField(
            model_name='client',
            name='driver_license_year',
            field=models.DateField(blank=True, null=True, verbose_name='License Year'),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_license_year',
            field=models.DateField(blank=True, null=True, verbose_name='License Year'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_milage',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=12, verbose_name='End Milage'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_milage',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=12, verbose_name='Start Milage'),
        ),
    ]
