# Generated by Django 5.1.4 on 2025-03-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0017_car_number_of_mile_client_driver_license_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_milage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='End Milage'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_milage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='Start Milage'),
        ),
    ]
