# Generated by Django 5.1.4 on 2025-03-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0018_alter_reservation_end_milage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='number_of_mile',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=12, verbose_name='mileage'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_milage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='End mileage'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_milage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='Start mileage'),
        ),
    ]
