# Generated by Django 5.1.4 on 2025-03-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0019_alter_car_number_of_mile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='number_of_mile',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=12, verbose_name='mileage'),
        ),
    ]
